#Plugin version. Please do not tamper
ConfigVersion: 0.8.1

#Config file for world world (UUID: 3571daf0-dff0-4b17-b657-7a7ec7047883)

#Wether or not a BloodMoon happens in this world
#Requires a server restart upon changes
IsBlacklisted: false
#Sets a permanent BloodMoon in this world
#Obviously the interval option is ignored when this is on
PermanentBloodMoon: false
#Interval in days between BloodMoons
BloodMoonInterval: 40
#Do items despawn upon death?
ItemDespawnUponDeath: true
#Does experience despawn upon death?
ExperienceDespawnsUponDeath: true
#Maximum item amount to drop per mob death
ItemDropsMaximum: 2
#Minimum item amount to drop per mob death
ItemDropsMinimum: 1
#Mob experience drop multiplicator. Whole number only
ExperienceDropMult: 5
#Mob damage multiplier. Whole number only
MobDamageMultiplicator: 3
#Mob health multiplier. Whole number only
MobHealthMultiplicator: 3
#Should there be a lightning effect on player death?
LightningEffectOnPlayerDeath: true
#Adds a lightning effect when a mob dies
LightningEffectOnMobDeath: true
#Should there be a jingle when a BloodMoon ends?
PlaySoundUponBloodMoonEnd: true
#Should there be periodic creepy sounds during a BloodMoon?
PlayPeriodicSoundsDuringBloodMoon: true
#Adds a dark tone during a BloodMoon
DarkenSky: true
#Plays a sound when a player gets hit
PlaySoundUponHit: true
#Plays a particle effect when a mob and / or player gets hit
PlayerHitParticleEffect: true
MobHitParticleEffect: true
#Effect of rain and thunder during the BloodMoon
ThunderDuringBloodMoon: true
#Prevents sleeping during a BloodMoon
PreventSleeping: true
#Prevents mob created by spawner from dropping any reward
MobsFromSpawnerNoReward: false
#Prevents special effects from being applied when a player raises their shield
ShieldPreventsEffects: true
#Mob spawn rate during a BloodMoon.
#0 means no mob at all, 25 is average, and anything above 100 is honestly insane
BloodMoonSpawnMobRate: 65
#Decides if a zombie boss will spawn each BloodMoon
EnableZombieBoss: true
#When in a permanent BloodMoon, how long (in ticks) before respawning zombie boss after death?
#20 ticks equals a second, 24000 ticks equals a minecraft day
ZombieBossRespawn: 24000
ZombieBossDamage: 24
ZombieBossExpMultiplier: 100
ZombieBossHealth: 12000
ZombieBossItemMultiplier: 24
#List of items that can drop, using the
#"[ITEM_CODE]:[STACK AMOUNT]:[WEIGHT]:$name [META NAME]:$desc [META DESCRIPTION]:$enchant [ENCHANTMENT LIST]" format
#$name, $desc and $enchant are of course optional
#The enchantment list argument is formatted as follow: "$enchant [ENCHANT NAME],[LEVEL];"
#The percent chance of an item dropping is equal to [item weight] / [total weight] * 100
#Please refer to https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html for the list of items
#Enchantment names are exactly as they appear in-game, except with "_" replacing spaces. Case is irrelevant
DropItemList:
  - "IRON_INGOT:3:6"
  - "IRON_BLOCK:1:2"
  - "GOLD_INGOT:3:6"
  - "GOLD_BLOCK:1:2"
  - "DIAMOND:3:6"
  - "DIAMOND_BLOCK:1:2"
  - "ANCIENT_DEBRIS:1:1"
  - "BLAZE_ROD:3:5"
  - "GHAST_TEAR:1:4"
#Here is an example of a special item drop with fire aspect I and sharpness III:
# - "DIAMOND_SWORD:1:1:$name Excalibur:$desc The legendary Excalibur$nSword of King Arthur:$enchant FIRE_ASPECT,1;sharpness,3"
#These are AOE powers affecting all players around the boss
#Accepted values are:
#LIGHTNING,[range],[cooldown]
#BLINK,[range],[cooldown]
#FIRE,[range],[cooldown],[duration]
#UNDERLING,[range],[cooldown],[amount]
#SPRINT,[duration],[cooldown],[amplifier]
#BLIND,[range],[cooldown],[duration]
#POISON,[range],[cooldown],[duration],[amplifier]
#WITHER,[range],[cooldown],[duration],[amplifier]
ZombieBossPowerSet:
  - "WITHER,12,20,5,1"
#Mob effects on hit. Format (with no spaces in between):
#[Effect],[Duration in seconds],[Effect amplifier. Use 1 if you're unsure]
#For a complete list of effects, refert to https://hub.spigotmc.org/javadocs/spigot/org/bukkit/potion/PotionEffectType.html
#Additional effects include: 'LIGHTNING'
ZOMBIEEffects:
  - "WITHER,8,1"
HUSKEffects:
  - "WITHER,8,1"
ZOMBIE_VILLAGEREffects:
  - "WITHER,8,1"
SKELETONEffects:
  - "WITHER,8,1"
CREEPEREffects:
  - "LIGHTNING"
SPIDEREffects:
  - "POISON,4,1"
  - "WITHER,8,1"
ZOMBIEBOSSEffects:
  - "WITHER,8,2"
  - "DARKNESS,5,1"
STRAYEffects:
  - "CONFUSION,3,1"
CAVE_SPIDEREffects:
  - "POISON,10,1"


#These commands will be ran right as a BloodMoon starts
#You must append a ;s, ;f or ;p at the end of the command:
#using ;s runs the command as the server. Once
#using ;f runs the command as the server, for each player. use $p as the player placeholder
#using ;p runs the command as the player, for each player. $p also applies
#For all options, $w will be replaced by the world name
#Note that these commands will be the very first and very last operations
#ran when starting and ending a BloodMoon
CommandsOnStart:
#  - "some command;s"
#Commands ran at the end of the BloodMoon
CommandsOnEnd:
#  - "command on player $p on world $w;p"

#Hordes parameter
#Are hordes even enabled in this world?
HordesEnabled: true
#The baseline spawn rate of hordes in ticks (1/5th of a second)
BaselineHordeSpawnrate: 165
#The variation of hordes spawn time in ticks
HordeSpawnrateVariation: 100
#Decides which mobs are allowed in hordes
HordeMobWhitelist:
 - "ZOMBIE"
 - "SKELETON"
 - "SPIDER"
 - "CREEPER"
 - "WITHER_SKELETON"
 - "STRAY"
 - "WITCH"
#The distance from players in block at which hordes will spawn
HordeSpawnDistance: 10
#The minimum number of mobs in a horde
HordeMinPopulation: 25
#The maximum number of mobs in a horde
HordeMaxPopulation: 55
