Template: PetOverlord
Settings:
  Default_Name: Mushroom Cow
  Entity_Type: MUSHROOM_COW
  Egg_Texture: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYTE2M2JjNDE2YjhlNjA1OGY5MmIyMzFlOWE1MjRiN2ZlMTE4ZWI2ZTdlZWFiNGFkMTZkMWI1MmEzZWMwNGZjZCJ9fX0=
Food:
  item_example:
    Item:
      Material: APPLE
    Saturation: 3.0
    Sound: ENTITY_GENERIC_EAT
    Particle:
      Name: HEART
      Data: ''
