Template: CombatOverlord
Settings:
  Default_Name: Wolf
  Entity_Type: WOLF
  Egg_Texture: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNjlkMWQzMTEzZWM0M2FjMjk2MWRkNTlmMjgxNzVmYjQ3MTg4NzNjNmM0NDhkZmNhODcyMjMxN2Q2NyJ9fX0=
Food:
  item_example:
    Item:
      Material: APPLE
    Saturation: 3.0
    Sound: ENTITY_GENERIC_EAT
    Particle:
      Name: HEART
      Data: ''
